version: '3'

services:
  firstbot:
    image: exponenci/firstbot:latest
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_NAME: ${DATABASE_NAME}

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --scope myscope
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
